export const data = [
    {
        "gtin": 93718134,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1014129,
        "Material_Description": "M/FOOD MINT JELLY 290G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10509,
        "Merchandise_Category": 105090210,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 30,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44342,
        "Stock": 2,
        "Stock_required": 10
    },
    {
        "gtin": 94130133,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1144619,
        "Material_Description": "BUMPER BAR BANANA 75G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10538,
        "Merchandise_Category": 105380104,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 10,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44424,
        "Stock": 0,
        "Stock_required": 10
    },
    {
        "gtin": 94204902,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 5291427,
        "Material_Description": "BUMPER BAR PEANUT CHOC TRAIL PROTEIN 75G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10538,
        "Merchandise_Category": 105380104,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 11,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44424,
        "Stock": 4,
        "Stock_required": 5
    },
    {
        "gtin": 20662020208,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1155761,
        "Material_Description": "P/NEWMAN DSRG CAESAR 250ML",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10509,
        "Merchandise_Category": 105090102,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 6,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 0,
        "Stock": 0,
        "Stock_required": 5
    },
    {
        "gtin": 8852511011349,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1129714,
        "Material_Description": "KEWPIE MAYONNAISE JAPAN 300G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10509,
        "Merchandise_Category": 105090103,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 1,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44421,
        "Stock": 4,
        "Stock_required": 6
    },
    {
        "gtin": 9300652804874,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1332874,
        "Material_Description": "SAN WEET-BIX CEREAL GLUTEN FREE 375G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10508,
        "Merchandise_Category": 105080110,
        "Aisle_Number": 501,
        "Bay_Number": 7,
        "Shelf_number": 1,
        "Slot_number": 16,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 0,
        "Stock": 6,
        "Stock_required": 10
    },
    {
        "gtin": 9310055103092,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 5241617,
        "Material_Description": "KELLOGGS VARIETY 8 PACK SACHETS 275G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10508,
        "Merchandise_Category": 105080109,
        "Aisle_Number": 501,
        "Bay_Number": 7,
        "Shelf_number": 1,
        "Slot_number": 1,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44417,
        "Stock": 0,
        "Stock_required": 3
    },
    {
        "gtin": 9414882431868,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1031692,
        "Material_Description": "ETA PEANUTS SALTED 200G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10531,
        "Merchandise_Category": 105310403,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 26,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44425,
        "Stock": 4,
        "Stock_required": 10
    },
    {
        "gtin": 9415077011230,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1028216,
        "Material_Description": "PAMS SALMON PINK KING 105G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10515,
        "Merchandise_Category": 105150101,
        "Aisle_Number": 501,
        "Bay_Number": 3,
        "Shelf_number": 1,
        "Slot_number": 19,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44424,
        "Stock": 5,
        "Stock_required": 14
    },
    {
        "gtin": 9415077035519,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1039324,
        "Material_Description": "PAMS OIL SPRAY CANOLA COOKING 200G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10511,
        "Merchandise_Category": 105110501,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 40,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44370,
        "Stock": 3,
        "Stock_required": 8
    },
    {
        "gtin": 9415077068654,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1038725,
        "Material_Description": "PAMS PEACH PIECES IN MANGO JELLY 125G 4S",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10530,
        "Merchandise_Category": 105300301,
        "Aisle_Number": 501,
        "Bay_Number": 4,
        "Shelf_number": 1,
        "Slot_number": 3,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44393,
        "Stock": 0,
        "Stock_required": 6
    },
    {
        "gtin": 9415077084487,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1167092,
        "Material_Description": "PAMS TOMATO SAUCE UPSIDE DOWN 560G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10509,
        "Merchandise_Category": 105090205,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 9,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44417,
        "Stock": 0,
        "Stock_required": 4
    },
    {
        "gtin": 9415077094677,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1044961,
        "Material_Description": "PAMS CLASSIC WHOLE EGG MAYO 443ML",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10509,
        "Merchandise_Category": 105090103,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 2,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44396,
        "Stock": 0,
        "Stock_required": 6
    },
    {
        "gtin": 9415077103195,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1028314,
        "Material_Description": "PAMS OLIVE OIL EXTRA VIRGIN 500ML",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10511,
        "Merchandise_Category": 105110103,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 35,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44357,
        "Stock": 0,
        "Stock_required": 10
    },
    {
        "gtin": 9415077103201,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1028312,
        "Material_Description": "PAMS OIL OLIVE EXTRA LIGHT 500ML",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10511,
        "Merchandise_Category": 105110102,
        "Aisle_Number": 501,
        "Bay_Number": 2,
        "Shelf_number": 1,
        "Slot_number": 33,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44347,
        "Stock": 0,
        "Stock_required": 9
    },
    {
        "gtin": 9415077104956,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 5233724,
        "Material_Description": "PAMS FINEST ALMOND BUTTER DARK CHOC 275G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10532,
        "Merchandise_Category": 105320303,
        "Aisle_Number": 501,
        "Bay_Number": 8,
        "Shelf_number": 1,
        "Slot_number": 28,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44383,
        "Stock": 0,
        "Stock_required": 8
    },
    {
        "gtin": 9415912171754,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 5291712,
        "Material_Description": "COOKIE TIME LOLLY CAKE 85G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10507,
        "Merchandise_Category": 105070305,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 6,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44425,
        "Stock": 0,
        "Stock_required": 5
    },
    {
        "gtin": 9416050581610,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1138155,
        "Material_Description": "MOTHER EARTH CASHEWS CHILLI/LIME 140G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10531,
        "Merchandise_Category": 105310401,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 33,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44425,
        "Stock": 0,
        "Stock_required": 8
    },
    {
        "gtin": 9421013441481,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1091563,
        "Material_Description": "JACK LINKS BEEF JERKY TERIYAKI 50G",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10531,
        "Merchandise_Category": 105310205,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 39,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44571,
        "Stock": 0,
        "Stock_required": 7
    },
    {
        "gtin": 9345156198036,
        "Site": 4997,
        "Store_Name": "Foodie Mart",
        "Article": 1091563,
        "Material_Description": "HEALTH+BEAUTY INSTANT HAND SANITISER",
        "Material_Type": "HAWA",
        "Department": 105,
        "Sub_Department": 10531,
        "Merchandise_Category": 105310205,
        "Aisle_Number": 501,
        "Bay_Number": 5,
        "Shelf_number": 1,
        "Slot_number": 39,
        "RRP_Ticket_Size": "ZELECTRONIC",
        "Simple_Promo_Ticket_Size": "ZELECTRONIC",
        "Ticket_Last_Printed": 0,
        "Last_Sold": 44571,
        "Stock": 0,
        "Stock_required": 7
    },
]